/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutComment: typeof import('@nutui/nutui')['Comment']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
  }
}
